### ISSUE TITLE
Observation.status

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/lab#113]
Add to guidance: 

The result SHALL never be empty. If there is no result, then the result SHALL contain a language specific text that indicates the reason of the missing result.
e.g. result pending, sample not received.

**Comment by bdc-ehealth** [comment]
@tomfiers Tom can you please give some more justification for this issue because Nico Vannieuwenhuyze (AMARON) thinks this is a deviation from normal HL7 practice.

**Comment by tomfiers** [comment]
I won't comment on how it is transmitted. I trust Nico on that ;) 
I'm just concerned with the end result which has to be clear as to why a result is missing: is it because the sample is not received (the specimen status should reflect this too) (and potentially thus never come) ,or is it because the sample is there and the result will be coming.
This is very important information for the receiver.

**Comment by bdc-ehealth** [comment]
Comment to Nico Vannieuwenhuyze 
The way of working by Tom Fiers is possible in the current definition of the profiles. Tom (as a clinical biologist) thinks this information is clinically important, but the way this is done will be different for every laboratory. Therefore we will keep this in the implementation guide.
