### ISSUE TITLE
In the test examples there are a lot of Loinc codes that are not in the Retam

### ISSUE THREAD

**Issue by MiekeNXH** [hl7-be/lab#140]
What is the planning for adding these? At the moment, we are showing the Loinc code on the screen because of a lack of label.

**Comment by bdc-ehealth** [comment]
@tomfiers ,

If there are missing LOINC codes in Retam, can the software vendors ask you and CAUCHIE Philippe <philippe.cauchie@chu-charleroi.be> to add these to Retam?

**Comment by tomfiers** [comment]
yes please send them, also include Ann Verdonck 
***@***.***> and ***@***.***

add: maybe, not necessarily : that depends if they ate useful for the 
broader community and not a variation of what is already there.

kind regards,

Tom


Op 5/09/2022 om 16:18 schreef Bart Decuypere (eHealth):

**Comment by bdc-ehealth** [comment]
@MiekeNXH 

As you can see from the answer by  Tom Fiers:

you can ask 

(mailto:ann.verdonck@uzleuven.be)
(mailto:tom.fiers@uzgent.be)
[philippe.cauchie@chu-charleroi.be](mailto:philippe.cauchie@chu-charleroi.be)

to add these

**Comment by MiekeNXH** [comment]
Isn't it more efficient that the lab's compare their list to the Retam and give a list of codes to add? We can only give the codes from the testcases that we encounter one by one. The codes that aren't sent to us will therefore not find their way to the Retam.

**Comment by bdc-ehealth** [comment]
This is a question we can ask Dr Alin Derom, the representative of the labs in Belgium ( @alinderom ).

Alin,

is this an option? Can we ask all labs to request Retam-codes for the tests they use? Maybe 
[ann.verdonck@uzleuven.be](mailto:ann.verdonck@uzleuven.be)
[tom.fiers@uzgent.be](mailto:tom.fiers@uzgent.be) @tomfiers 
[philippe.cauchie@chu-charleroi.be](mailto:philippe.cauchie@chu-charleroi.be)
will be swamped in work if we do so?

**Comment by alinderom** [comment]
The new lab result format in FHIR using RETAM, UCUM & SNOMED has as purpuse to make the exchange of messages easy & interchangeable. 
There is an agreemenet that the primary code-provider for the test results will be RETAM, if there is no RETAM code then another code-provider can be used (e.g. LOINC, Medigest, own lab code table, ...). There is no limit in the number of different code-providers that can be added to a result in 1 message. But if there exists a RETAM code it must be used and must be the first.

In order to be able to compare all labs should use the same code-provider and the same code. Because LOINC has a (to) extensive list of codes Belgium has choosen to use it's own subset (RETAM). It is in the advantage of everybody that as many tets are into this RETAM table.
Therefore I repeat that every missing test that already has a LOINC code should be eligible to be added in the Retam tabel. Of course adding all existing LOINCcodes would be a lot (and useless) work. And of course we don't want "RBC by full automatic analyzer" & "RBC by semi-automatic analyzer" as possibility for RBC (or do we?). 
At least in the beginning (2023) the most frequent tests (that have a LOINC code) should be in the RETAM table. I have attached a screenshot of all analyses of our reporting to general practitioners (clinical biology + anatomapathology) for the last 3 months. I don´t know if that screenshot will be visible in GITHUB but as of today only 65% of our results an 24% of our reported tests have a RETAM code . But I cannot guarantee all existing RETAM codes are configured in our LIS,

![Rapporteerbare analyse zonder Retam ](https://user-images.githubusercontent.com/25255092/188592612-baff9bc6-0878-48e9-988c-16c217df16f1.png)

conclusion : 
1) add as many tests that already have a LOINC-code as possible tests in the table (of course the most frequent (if known) tests first)
2) if "tests" like lipemic index & interpretation thyroid function have another way of reprting , this should be mentioned claerly somewhere for those who don't known it (yet). There are LIS systems where this information or interpretation is a "test". 

PS : My personal opinion is that at least every test that is reported more than 300 times a year by al lab & has a LOINC code should be in the RETAM table.

**Comment by filipv-nh** [comment]
I understand the reasoning from Alain, but before we continue programming we need to be sure what the official BE approach is going to be on this topic. If we keep on allowing other 'code-providers' to be used in the fhir messages for the Lab Results, there will be no incentive whatsoever for the labs to start using the RETAM codes and on the receiving application we will be confronted again with a plethora of different reports that cannot be compared over labs.

So, until there is a firm and official statement on what we have to implement in our GP application, we wil hold the further development.

**Comment by filipv-nh** [comment]
Ok, thanks for the clarification Alin! Especially the 'MUST" is appreciated. Let's discuss this indeed further in the WG.

Just an additional note irt our current integration efforts within our GP: only results that are encoded with the RETAM/UCUM codes will be stored in our internal structured result server. Other non-stuctured results can be displayed but cannot be stored in that result server. As a consequence these results will not be processed or compared with each other, or over labs.

**Comment by alinderom** [comment]
FIlip, the fact that non-structured results can't be compared to other (sturctured or not-structured) is "logical". As long as anybody who looks at the report sees the unstructured information there is no problem. Also when a report is forwarded (by one GP to another GP with another software) this unstructered information must be within the message. 
This fact/limitation is a good incentive for every lab and LIS-provider to foresee that all results can be exchanged in a structured way.

**Comment by tomfiers** [comment]
that is indeed logical. 
-------- Oorspronkelijk bericht --------Van: "Filip Vertommen (nexuzhealth)" ***@***.***> Datum: 6/09/2022  12:53  (GMT+01:00) Aan: hl7-be/lab ***@***.***> Cc: tomfiers ***@***.***>, Mention ***@***.***> Onderwerp: Re: [hl7-be/lab] In the test examples there are a lot of Loinc codes that are not in the Retam (Issue #140) 
Ok, thanks for the clarification Alin! Especially the 'MUST" is appreciated. Let's discuss this indeed further in the WG.
Just an additional note irt our current integration efforts within our GP: only results that are encoded with the RETAM/UCUM codes will be stored in our internal structured result server. Other non-stuctured results can be displayed but cannot be stored in that result server. As a consequence these results will not be processed or compared with each other, or over labs.
