### ISSUE TITLE
Unique patient identifier for non Belgians

### ISSUE THREAD

**Issue by tomto66** [hl7-be/lab#19]
Cookbook says to use RRN to identify patients - but quid foreigners?  Some foreigners will have a BIS number and that can be used, but not all foreigners will have that. What to do with those who do not?

**Comment by alinderom** [comment]
I suggest the persons with BIS numbers will be identified with the BIS number (is also unique)
Do not use TER numbers;  Those are only for COVID and are not unique (1 person can have several TER numbers)
In other cases I suggest : if available and unique mention the foreign unique identidfcation with correct issuing.authority
additional in other cases : mention the unique internal (lab or hospital) identifcation with a unique issuing.authority (format must be agreed upon eG : code for Belgium + code of hospital/lab+code_of_LIS (code of LIS because when changing/merging LIS systems the unique codes could differ)

**Comment by costateixeira** [comment]
We do not have to choose the best identifier, or even a "priority" of identifiers.
We can have NISS and/or BIS. 
About the issuing authority, that would be a NamingSystem resource that we can produce. We already have some NamingSystems

**Comment by tomto66** [comment]
Please take into account that we may have subject that have neither NISS
nor BIS numbers!  We would still need to cater for those.

**Comment by costateixeira** [comment]
Concretely, we should add in the documentation that ANY identifier can be used, as long as the identifier namingsystem is identified - for adding NamingSystems, we should go back to the Core / Patient Dossier WGs.

We should add examples showing how the slicing works for any number and any type of identifier.
One example with BIS
Another exampel with SSIN

We can ask the adequate WG to add the BIS slice on BePatient

**Comment by bdc-ehealth** [comment]
NamingSystem: url determined by the lab system
Use the lab RIZIV number + dash + patient number in the system.
