### ISSUE TITLE
Error processing Unit

### ISSUE THREAD

**Issue by Charlottedp** [hl7-be/lab#194]
Sometimes we get a validation error in the testing tool that concerns the Unit.
Example: Error processing Unit: 'milj/tube': The unit "milj" is unknown at character 1; The code "milj/tube" is not valid in the system http://unitsofmeasure.org; The code provided (http://unitsofmeasure.org#milj/tube) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r4) for 'http://unitsofmeasure.org#milj/tube'

But the visualization of the report looks fine. Can we just ignore this error? If not, what does it mean?

**Comment by bdc-ehealth** [comment]
@Charlottedp 

This means that the unit you are using is not a valid UCUM unit. In order to be able to correctly compare and calculate with the results of tests, you have to express your result using UCUM units (if it is measurable). You can find the explanation here: https://ucum.org/ . If you give me the LOINC code of the test you are processing, I can help you to look up the appropriate UCUM unit. If there is no LOINC code for the test, post the file here or you can send me the file at 'support@be-ehealth-standards.atlassian.net' if it contains GDPR sensitive information. I will try to debug it, and send you some suggestions.
