### ISSUE TITLE
Test case on Github invalid

### ISSUE THREAD

**Issue by khackincita** [hl7-be/lab#199]
Hello @bdc-ehealth ,

As mentioned in the issue [ESI-224](https://be-ehealth-standards.atlassian.net/servicedesk/customer/portal/2/ESI-224), I tried the Visualization Tool on an existing test case :
https://github.com/hl7-be/lab/blob/master/testing/MIPS/UZG_scenario1/1d_bundle_22030216201.json

The validation failed :
![image](https://github.com/hl7-be/lab/assets/135993394/c5320fa3-62b5-4cf4-af2c-826ce598e994)

Can you check why ?

Best regards

**Comment by bdc-ehealth** [comment]
I checked this, and the problem is not caused by the file, but by the changed validation rules. There is a new requirement that for codes in general (and thus also for LOINC codes) the values in the discription field should correspond with the value available on the terminology server.  For the lab report, this is not always the case, because labs are allowed (although not recommended) to use their own display values. In order to allow this, we will have to add an extra parameter to the validator (see: https://github.com/hl7-be/lab/issues/199 )

**Comment by bdc-ehealth** [comment]
We wait for the 6.0.16 release of the international validator to be able to fix this.

**Comment by bdc-ehealth** [comment]
6.0.16 is available and tested. Now we have to change our code to add the parameter.

**Comment by bdc-ehealth** [comment]
@khackincita Hi Kevin, we integrated the new validator in our code, and all should be well again!
