### ISSUE TITLE
Test case 2F4

### ISSUE THREAD

**Issue by frederic-istace** [hl7-be/lab#207]
I have submitted a message under the ID 470 for test case 2F4 (NISS number 00011799950). The FHIR test server displays "unknown test case". I suppose, it's because there is no reference file attached to this test case yet? If so, can somebody check if our message is valid?

**Comment by bdc-ehealth** [comment]
@frederic-istace 

Indeed, you are right. I was on holiday last week, so I will try to process your message this week. If it is OK, it will serve as a reference file for this case. Thanks for helping out!

**Comment by frederic-istace** [comment]
@bdc-ehealth 

I have submitted some more tests today. Could you pleast also have a look at them?

![New tests submitted](https://github.com/hl7-be/lab/assets/97762183/993e2f42-ba81-46f3-aaa6-f56a0a2f7e77)

**Comment by bdc-ehealth** [comment]
@frederic-istace 
2F4 -> the file contains "HH" instead of "H", so this one cannot be accepted as a reference file

**Comment by frederic-istace** [comment]
@bdc-ehealth 
Indeed, 468 and 469 are wrong but 470 should be correct, I think.

**Comment by bdc-ehealth** [comment]
@frederic-istace ,

I reviewed all your files! Thanks for the large contribution! Your main point of attention is the use of UCUM units. Check this site for more information: https://ucum.org/

**Comment by frederic-istace** [comment]
@bdc-ehealth 

Thank you for your feedback. I have submitted a new example for test case 8A under ID 495. Could you please check if this one is ok now?

**Comment by bdc-ehealth** [comment]
@frederic-istace 

There is one thing that escaped my attention, and that is that you are still using the old references to some Belgian Profiles. The tool does not consider this as an error, but only as something unknown.

If you do the validation using the Visualization tool, you will see things like this:

Information @ Bundle.entry[1].resource/*DiagnosticReport/ba4bba75-204a-4f67-91ad-5e7bc24a357c*/.meta.profile[0] (line 77, col103): Canonical URL 'https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-laboratory-report' does not resolve.

That is because https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-laboratory-report should be replaced by https://www.ehealth.fgov.be/standards/fhir/*lab*/StructureDefinition/be-laboratory-report

https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-patient should be https://www.ehealth.fgov.be/standards/fhir/*core*/StructureDefinition/be-patient

https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-laboratory-report-composition should be https://www.ehealth.fgov.be/standards/fhir/*lab*/StructureDefinition/be-laboratory-report-composition

https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-servicerequest should be  https://www.ehealth.fgov.be/standards/fhir/*lab*/StructureDefinition/be-servicerequest
    
https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-organization should be 
https://www.ehealth.fgov.be/standards/fhir/*core*/StructureDefinition/be-organization

https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-observation-laboratory should be
https://www.ehealth.fgov.be/standards/fhir/*lab*/StructureDefinition/be-observation-laboratory

https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-specimen-laboratory should be
https://www.ehealth.fgov.be/standards/fhir/*lab*/StructureDefinition/be-specimen-laboratory

**Comment by bdc-ehealth** [comment]
@frederic-istace 

Also beware of this one:

https://www.ehealth.fgov.be/standards/core/fhir/NamingSystem/nihdi should be https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/nihdi

**Comment by frederic-istace** [comment]
@bdc-ehealth 

I have fixed the references to the Belgian profiles and started to resend the relevant messages. Could you please check why my last message for test case 2A1 is still marked as failed? Looking in the "diff result" and in the "payload", it seems to me that the problem is in the condition which is checked by the test case and not in the message any more.

**Comment by bdc-ehealth** [comment]
@frederic-istace 

You are right. I modified the check, and retried the test with the last but one file. It passes now.

**Comment by bdc-ehealth** [comment]
@frederic-istace There are no problems with the old files anymore (as you can see yourself). I will check the ones for which there no reference file yet.

**Comment by bdc-ehealth** [comment]
@frederic-istace 

518, 8E -> OK, thank you for the file!
519, 2C -> Can you use ucum style empty units if you use quantity? see also issue: https://github.com/hl7-be/lab/issues/36
520, 1E3 -> OK, thank you for the file!
521, 1B -> OK, thank you for the file! (Personally, I think both the PDF, and the visualization is confusing, but technically the file is OK)

**Comment by frederic-istace** [comment]
@bdc-ehealth  
I have submitted a new message under ID 531 for test case 2C.

Could you please also have look at the messages 522 (3B), 523 (3C), 524 (3D), 526 (2H), 527 (41A) and 529 (41C) ?

**Comment by bdc-ehealth** [comment]
@frederic-istace,

For 521: see the comments of one of our biologists:

Bonjour Bart, 

Tu as raison ce n’est pas bon, car on ne voit pas correctement sur quel échantillon le glucose est dosé.  

Le premier (75 mg/dL) on peut supposer que c’est le glucose sur sérum ou plasma 

Ensuite glucose sur urine : dosage et débit par 24h – à noter que le volume de collecte n’apparaît pas sur le pdf. Pour moi c’est nécessaire. 

Le dernier est très probablement le glucose sur LCR mais l’échantillon doit absolument être précisé, par exemple via un titre comme pour l’urine. A noter que certains proposent, chaque fois que c’est possible, de désigner l’échantillon par le nom spécifique : glycémie , glycosurie, glycorachie. 

Sincèrement, Philippe 

De : [Bart.Decuypere@ehealth.fgov.be](mailto:Bart.Decuypere@ehealth.fgov.be) <[Bart.Decuypere@ehealth.fgov.be](mailto:Bart.Decuypere@ehealth.fgov.be)> 
Envoyé : vendredi 4 août 2023 17:58
À : [Tom.Fiers@uzgent.be](mailto:Tom.Fiers@uzgent.be); [philippe.cauchie@skynet.be](mailto:philippe.cauchie@skynet.be); [philippe.cauchie@chu-charleroi.be](mailto:philippe.cauchie@chu-charleroi.be)
Cc : [peter.laridon@ehealth.fgov.be](mailto:peter.laridon@ehealth.fgov.be); [Jean-Michel.Polfliet@ehealth.fgov.be](mailto:Jean-Michel.Polfliet@ehealth.fgov.be)
Objet : Testcase 1B - twijfelgeval - cas douteux

Tom, Philippe,

Technisch bekeken voldoet deze file aan de acceptatiecriteria: hij heeft 3 glucosemetingen op 3 verschillende stalen, maar in de visualisatie en in de PDF is dat volgens mij onduidelijk.

Point de vue technique, ce fichier a tous les éléments pour réussir: il y a 3 mesures de glucose, liés à 3 échantillons différents, mais au niveau visualisation, et même dans le PDF, pour moi, ce n’est pas très clair.

Wat moet ik hiermee doen ? Qu’est-ce je fais avec ceci?

**Comment by bdc-ehealth** [comment]
@frederic-istace 
522, 3B -> Can you use ucum style empty units if you use quantity? see also issue: https://github.com/hl7-be/lab/issues/36
523, 3C -> OK, thank you for the file!
524, 3D -> Can you use ucum style empty units if you use quantity? see also issue: https://github.com/hl7-be/lab/issues/36
526, 2H -> OK, thank you for the file!
527, 41A -> OK, thank you for the file!
529, 41C -> OK, thank you for the file!

**Comment by frederic-istace** [comment]
@bdc-ehealth 
I have resent messages for test cases 3B and 3D under ID 586 and 587.
