### ISSUE TITLE
Bundle.entry.fullUrl

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/lab#291]
Hi,

I might have missed it but what is the status on the bundle.entry.fullUrl issue?

If i recall correctly FHIR R4 has become more strict and does no longer accept relative URLs (e.g. Patient/123). Instead, a full URL or a UUID should be used.

The test server still accepts relative URLs. However, the vizualizer gives an error.

My questions are:

1. Is this communicated to the labs that the vizualizer gives errors? We receive a lot of questions about it.
2. What action should the suppliers take? Should we change our relative URLs? Should we use a UUID then?
3. If the relative URL can no longer be used, who will update the examples?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
@thibaultmh ,

The status with the 'fullUrl' problem is as follows (for the history, check https://github.com/hl7-be/lab/issues/278 ).

Due to evolutions in the international tooling, we are forced to label the 'fullUrl's that are relative as errors. Previously they were not detected. Because we cannot impose this change during Phase 1 (i.e. sending via the eHealthBox) on all labs (we do not want to change the rules during the game), we decided to be lenient on this error, but still display the error.

From Phase 2 on (i.e. sharing using the HUB/METAHUB system) we will no longer allow the 'fullUrl' errors in the test server. That means that we will request all LIS soft vendors to remove all "relative" Urls from that moment on. Phase 2 will be started from the moment that the adoption of Phase 1 is sufficient (i.e. there is no fixed date now, but we expect this to be before 2025).

**Comment by thibaultmh** [comment]
OK thank you
