### ISSUE TITLE
Given name (patient / practitioner)

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#31]
In the example FHIR, when a person has more than one first name, the first names are seperately named in different given-fields.
E.g.: Name.Family = 'Janssen' - Name.Given = 'Jan' - Name.Given = 'Louis'
Is it obligated to seperate the names in different fields? Or can we do the following?
E.g.: Name.Family = 'Janssen' - Name.Given = 'Jan Louis'

**Comment by costateixeira** [comment]
There is nothing forcing us to choose either. AFAIK, a name like "Pieter-Jan" is just one name, the same with "Jean-Pierre"
We could provide some (national) guidance on this, because it will impact patient reconciliation. Not on the Labo, but I'd be happy to escalate this question to a common FHIR group (FHIR core, FHIR Infrastructure) where this can be discussed for all profiles.

**Comment by bdc-ehealth** [comment]
In EID it is in one field, both for given names and family names. Do we go for given name in one field and family name in one field, as in the EID.

**Comment by bdc-ehealth** [comment]
WG agrees with putting the given names in one field -> see EID.
