### ISSUE TITLE
Which and how many other coding systems do we include in the observations?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/lab#34]
Codings are arrays, so we can do multiple ones.
Proposal: LOINC + Medidoc + native code of sender?

**Comment by bdc-ehealth** [comment]
You can find the use of coding systems in this URL: https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/guidance.html#use-of-retam-codes

**Comment by bdc-ehealth** [comment]
Comment by Alexis Van Zeveren:

Please add that a conversion table between the Loinc and old codes will be provided, to help the receivers with the conversion, so end users can compare new results in Loinc with older results in other codes

**Comment by tomto66** [comment]
Quick comment to document opinion of Tom Fiers (meeting POC group dd 24/11/2021) : every lab sends in its own coding system.  Consequence is that receivers that work with multiple labs may not be able to plot same analyses in cumulative report due to different units (and also different LOINC codes of course)

**Comment by bdc-ehealth** [comment]
WG We use the system as described here: https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/guidance.html#use-of-retam-codes . Other mappings can be added to the retam-table. The lab can (not mandatory) add the lab code  or an older code, if it is available.
